version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: blog_backend
    ports:
      - '8000:8000'
    volumes:
      - ./:/var/www/html
      - vendor_data:/var/www/html/vendor
    depends_on:
      - mysql
    networks:
      - blognet

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/node/Dockerfile
    container_name: blog_frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    networks:
      - blognet

  mysql:
    image: mysql:8.0
    container_name: blog_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: blog
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blognet

  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    ports:
      - '80:80'
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - blognet

volumes:
  mysql_data:
  vendor_data:

networks:
  blognet: