name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        echo "::group::DEBUG: SSH config info"
        echo "SSH_HOST: '${{ secrets.SSH_HOST }}'"
        echo "SSH_USER: '${{ secrets.SSH_USER }}'"
        echo "TARGET_DIR: '${{ secrets.TARGET_DIR }}'"
        echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d | head -n 5
        echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d | wc -l
        echo "::endgroup::"

        echo "Trying to scan host..."
        ssh-keyscan -v -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts


    - name: Deploy via rsync
      run: 
        rsync -e "ssh -o StrictHostKeyChecking=no" -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_DIR }}